disallowed-methods = [
  { path = "std::thread::Builder::new", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "std::thread::spawn", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_current_thread", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_multi_thread", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Builder::new_multi_thread_alt", reason = "use one of the `nativelink-util::task` functions instead", allow-invalid = true }, # Can be invalid because depends on feature flags
  { path = "tokio::runtime::Runtime::block_on", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::new", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::spawn", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::runtime::Runtime::spawn_blocking", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::spawn", reason = "use `nativelink-util::task::spawn` or `nativelink-util::task::background_spawn` instead" },
  { path = "tokio::task::block_in_place", reason = "use one of the `nativelink-util::task` functions instead" },
  { path = "tokio::task::spawn", reason = "use `nativelink-util::task::spawn` or `nativelink-util::task::background_spawn` instead" },
  { path = "tokio::task::spawn_blocking", reason = "use `nativelink-util::task::spawn_blocking` instead" },
  { path = "tokio::task::spawn_local", reason = "use one of the `nativelink-util::task` functions instead" },
]
msrv = "1.93.0"
