#:schema ../tools/cargo-with-detailed-deps.json
lints.workspace = true

[package]
edition = "2024"
name = "nativelink-util"
version = "0.7.10"

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-error = { path = "../nativelink-error" }
nativelink-metric = { path = "../nativelink-metric" }
nativelink-proto = { path = "../nativelink-proto" }

async-trait = { version = "0.1.88", default-features = false }
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
bitflags = { version = "2.9.0", default-features = false }
blake3 = { version = "1.8.0", features = ["mmap"], default-features = false }
bytes = { version = "1.10.1", default-features = false }
futures = { version = "0.3.31", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
humantime = { version = "2.3.0", default-features = false }
hyper = { version = "1.6.0", default-features = false }
hyper-util = { version = "0.1.11", default-features = false }
lru = { version = "0.16.0", default-features = false }
mock_instant = { version = "0.5.3", default-features = false }
opentelemetry = { version = "0.29.0", default-features = false }
opentelemetry-appender-tracing = { version = "0.29.1", default-features = false }
opentelemetry-http = { version = "0.29.0", default-features = false }
opentelemetry-otlp = { version = "0.29.0", default-features = false, features = [
  "grpc-tonic",
  "logs",
  "metrics",
  "trace",
  "zstd-tonic",
] }
opentelemetry-semantic-conventions = { version = "0.29.0", default-features = false, features = [
  "default",
  "semconv_experimental",
] }
opentelemetry_sdk = { version = "0.29.0", default-features = false }
parking_lot = { version = "0.12.3", features = [
  "arc_lock",
  "send_guard",
], default-features = false }
pin-project = { version = "1.1.10", default-features = false }
pin-project-lite = { version = "0.2.16", default-features = false }
prost = { version = "0.13.5", default-features = false }
prost-types = { version = "0.13.5", default-features = false, features = [
  "std",
] }
rand = { version = "0.9.0", default-features = false, features = [
  "thread_rng",
] }
rlimit = { version = "0.10.2", default-features = false }
serde = { version = "1.0.219", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
tempfile = { version = "3.20.0", default-features = false }
tokio = { version = "1.44.1", features = [
  "fs",
  "io-util",
  "rt-multi-thread",
  "signal",
], default-features = false }
tokio-stream = { version = "0.1.17", features = [
  "fs",
], default-features = false }
tokio-util = { version = "0.7.14", default-features = false }
tonic = { version = "0.13.0", features = [
  "tls-native-roots",
  "tls-ring",
  "transport",
], default-features = false }
tower = { version = "0.5.2", default-features = false }
tracing = { version = "0.1.41", default-features = false }
tracing-opentelemetry = { version = "0.30.0", default-features = false, features = [
  "metrics",
] }
tracing-subscriber = { version = "0.3.19", features = [
  "ansi",
  "env-filter",
  "json",
], default-features = false }
uuid = { version = "1.16.0", default-features = false, features = [
  "serde",
  "v4",
  "v6",
] }
walkdir = { version = "2.5.0", default-features = false }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

http-body-util = { version = "0.1.3", default-features = false }
pretty_assertions = { version = "1.4.1", features = [
  "std",
], default-features = false }
rand = { version = "0.9.0", default-features = false, features = [
  "thread_rng",
] }
serde_json = { version = "1.0.140", default-features = false }
tracing-test = { version = "0.2.5", default-features = false, features = [
  "no-env-filter",
] }

[package.metadata.cargo-machete]
# Used by nativelink_test macro
ignored = ["tracing-test"]
