[package]
name = "nativelink-util"
version = "0.2.0"
edition = "2021"

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }

async-lock = "3.3.0"
async-trait = "0.1.77"
blake3 = "1.5.0"
bytes = "1.5.0"
futures = "0.3.30"
hex = "0.4.3"
log = "0.4.21"
lru = "0.12.3"
parking_lot = "0.12.1"
pin-project-lite = "0.2.13"
prometheus-client = "0.21.2"
prost = "0.12.3"
prost-types = "0.12.3"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.35.1", features = [ "sync", "fs", "rt", "time", "io-util", "macros" ] }
tokio-util = { version = "0.7.10" }
tonic = { version = "0.11.0", features = ["tls"] }
tracing = "0.1.40"

[dev-dependencies]
pretty_assertions = "1.4.0"
rand = "0.8.5"
mock_instant = "0.3.1"
