[package]
name = "nativelink-util"
version = "0.5.1"
edition = "2021"

[features]
enable_tokio_console = []

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }
async-lock = { version = "3.4.0", features = ["std"], default-features = false }
async-trait = "0.1.80"
bitflags = "2.5.0"
blake3 = { version = "1.5.1", features = ["mmap"] }
bytes = { version = "1.6.0", default-features = false }
pin-project = "1.1.5"
# TODO(aaronmondal): This is the commit that migrates tonic 0.11 to 0.12. Use a
#                    regular version once console-subscriber 0.4.0 is released.
#                    Commit: https://github.com/tokio-rs/console/commit/5f6faa2
#                    Release PR: https://github.com/tokio-rs/console/pull/576
console-subscriber = { git = "https://github.com/tokio-rs/console", rev = "5f6faa2" , default-features = false }
futures = { version = "0.3.30", default-features = false }
hex = { version = "0.4.3", default-features = false }
hyper = "1.4.1"
hyper-util = "0.1.6"
lru = { version = "0.12.3", default-features = false }
parking_lot = "0.12.3"
pin-project-lite = "0.2.14"
prost = { version = "0.13.1", default-features = false }
prost-types = { version = "0.13.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.204", default-features = false }
sha2 = { version = "0.10.8", default-features = false }
tokio = { version = "1.38.0", features = ["fs", "rt-multi-thread", "signal", "io-util"], default-features = false }
tokio-stream = { version = "0.1.15", features = ["fs"], default-features = false }
tokio-util = { version = "0.7.11" }
tonic = { version = "0.12.0", features = ["transport", "tls"], default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", features = ["ansi", "env-filter", "json"], default-features = false }
uuid = { version = "1.8.0", default-features = false, features = ["v4", "serde"] }
mock_instant = "0.3.2"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

http-body-util = "0.1.2"
pretty_assertions = { version = "1.4.0", features = ["std"] }
rand = { version = "0.8.5", default-features = false }
