[package]
name = "nativelink-metric-macro-derive"
version = "0.5.3"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.86", default-features = false }
quote = { version = "1.0.37", default-features = false }
syn = { version = "2.0.79", default-features = false }
