---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nativelink
  template:
    metadata:
      labels:
        app: nativelink
    spec:
      containers:
        - name: nativelink
          # This image will be edited by kustomize.
          image: nativelink
          env:
            - name: RUST_LOG
              value: info
          ports:
            - containerPort: 9090
            - containerPort: 50051
            - containerPort: 50052
            - containerPort: 50061
          volumeMounts:
            - name: nativelink-config
              mountPath: /nativelink-config.json
              subPath: nativelink-config.json
            - name: tls-volume
              mountPath: /root
              readOnly: true
          args: ["/nativelink-config.json"]
      volumes:
        - name: nativelink-config
          configMap:
            name: nativelink-config
        - name: tls-volume
          secret:
            secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nativelink
spec:
  selector:
    app: nativelink
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: grpcs
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: worker-api
      protocol: TCP
      port: 50061
      targetPort: 50061
