---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelink-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nativelink-worker
  template:
    metadata:
      labels:
        app: nativelink-worker
    spec:
      initContainers:
        - name: nativelink-worker-init
          # This image will be edited by kustomize.
          image: nativelink-worker-init
          args: ["/shared/nativelink"]
          volumeMounts:
            - name: shared
              mountPath: /shared
      containers:
        - name: nativelink-worker
          # This image will be edited by kustomize.
          image: nativelink-worker
          env:
            - name: RUST_LOG
              value: info
            - name: NATIVELINK_ENDPOINT
              value: nativelink
          volumeMounts:
            - name: worker-config
              mountPath: /worker.json
              subPath: worker.json
            - name: shared
              mountPath: /shared
          command: ["/shared/nativelink"]
          args: ["/worker.json"]
      volumes:
        - name: shared
          emptyDir: {}
        - name: worker-config
          configMap:
            name: worker
---
apiVersion: v1
kind: Service
metadata:
  name: nativelink-worker
spec:
  selector:
    app: nativelink-worker
  clusterIP: None
