[package]
name = "nativelink-config"
version = "0.4.0"
edition = "2021"

[dependencies]
byte-unit = "5.1.4"
humantime = "2.1.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json5 = "0.1.0"
shellexpand = "3.1.0"
