---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 2m
  path: "./kubernetes/resources/cert-manager"
  prune: true
  force: true
  retryInterval: 20s
  # Don't set targetNamespace for this one as the cert-manager kustomization
  # needs to create a cert-manager namespace. The flux resources will live in
  # the flux-system namespace.
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink-infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 24h
  path: "./kubernetes/vendor/olm"
  prune: true
  force: true
  retryInterval: 20s
  # Don't set targetNamespace for this one as OLM manages this itself.
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink-infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: telemetry-operators
  namespace: flux-system
spec:
  interval: 24h
  path: "./kubernetes/vendor/telemetry"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: operators
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink-infra
    namespace: flux-system
  dependsOn:
    - name: olm
