---
name: Cargo Native

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/styles/**'
      - 'web/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo-native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        toolchain: [stable]
    name: ${{ matrix.os }} / ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: >- # v4.2.2
          actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Rust toolchain
        run: rustup update && rustup default ${{ matrix.toolchain }}
        shell: bash

      - name: Rust cache
        # https://github.com/Swatinem/rust-cache/releases/tag/v2.8.1
        uses: Swatinem/rust-cache@c9119007a19252f0981aef1785db9b0dd6f373c0

      - name: Build on ${{ runner.os }}
        run: cargo build --all --profile=smol

      - name: Test on ${{ runner.os }}
        run: cargo test --all --profile=smol
