---
name: Vale

on: [pull_request]

permissions: read-all

jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Run Vale
        uses: >- # Custom commit, last pinned 2024.06.06.
          errata-ai/vale-action@91ac403e8d26f5aa1b3feaa86ca63065936a85b6
        with:
          filter_mode: file
          reporter: github-pr-check
          reviewdog_url: https://github.com/reviewdog/reviewdog/releases/download/v0.17.5/reviewdog_0.17.5_Linux_x86_64.tar.gz
